image: Visual Studio 2017

init:
  - ps: $env:APPVEYOR_SAVE_CACHE_ON_ERROR=true

before_build:
  - vcpkg install zlib:x86-windows
  - vcpkg install zlib:x86-windows-static

build:
  project: VGMPlay/VGMPlay.sln
  verbosity: quiet
  
platform:
  - Win32

configuration:
  - Release-static
  - Release

artifacts:
  - path: 'Release'
    name: release$(APPVEYOR_CONFIGURATION).zip
    type: zip

cache: c:\tools\vcpkg\installed\