image: Visual Studio 2017

environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true

before_build:
  - vcpkg install zlib:x86-windows
  - vcpkg install zlib:x86-windows-static

build:
  project: VGMPlay/VGMPlay.sln
  verbosity: quiet
  
platform:
  - Win32

configuration:
  - Release-static
  - Release

artifacts:
  - path: VGMPlay\Release-static
    name: vgmplay-$(APPVEYOR_CONFIGURATION).zip
    type: zip

  - path: VGMPlay\Release_win32
    name: vgmplay-$(APPVEYOR_CONFIGURATION).zip
    type: zip
cache: c:\tools\vcpkg\installed\

after_build:
  - ps: Get-ChildItem -Recurse *.exe