image: Visual Studio 2017

before_build:
  - cd c:\tools\vcpkg
  - vcpkg integrate install
  - vcpkg install zlib:x86-windows-static

build:
  project: VGMPlay/VGMPlay.sln
  verbosity: quiet
  
configuration:
  - Release

artifacts:
  - path: '**\*.exe'
    name: release-x64
    type: zip
